sudo: false
language: go
go:
- 1.4
- tip

cache:
  directories:
  - $HOME/gcloud/
env:
  - PATH=$PATH:$HOME/gcloud/google-cloud-sdk/bin
    TEST_PROJECT_ID=cloud-samples-tests
    TEST_BUCKET_NAME=cloud-samples-tests-bucket
    GOOGLE_APPLICATION_CREDENTIALS=client_secrets.json

before_install:
#ENCRYPT YOUR PRIVATE KEY (If you need authentication)
# 1. Install and login to the Travis CLI:
#       $ gem install travis
#       $ travis login
# 2. Move your json private key to client_secrets.json
# 3. Run:
#       $ travis encrypt-file client_secrets.json --add
# 4. Commit changes:
#       $ git add client_secrets.json.enc
#       $ git commit client_secrets.json.enc .travis.yml
- openssl aes-256-cbc -K $encrypted_bedb497efe4e_key -iv $encrypted_bedb497efe4e_iv -in client_secrets.json.enc -out "$TRAVIS_BUILD_DIR/client_secrets.json" -d || exit 1
- if [ ! -d $HOME/gcloud/google-cloud-sdk ]; then
        mkdir -p $HOME/gcloud &&
        wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz --directory-prefix=$HOME/gcloud &&
        cd $HOME/gcloud &&
        tar xzf google-cloud-sdk.tar.gz &&
        printf '\ny\n\ny\ny\n' | ./google-cloud-sdk/install.sh &&
        cd $TRAVIS_BUILD_DIR;
  fi
- gcloud -q components update
- gcloud -q auth activate-service-account --key-file client_secrets.json
  # Reset this env variable because the go build in travis resets
  # TRAVIS_BUILD_DIR to the GOPATH.
- export GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/client_secrets.json

install:
#Add app specific setup here
#Use '-q' to disable interactive prompts

script:
#Test and/or deploy your app with gcloud commands here!
